import React, { useState, useRef, useEffect } from 'react';
import { ShieldAlert, XCircle } from 'lucide-react';

export default function TwoFactorModal({ isOpen, onClose, onVerify }) {
    const [code, setCode] = useState(['', '', '', '', '', '']);
    const [isVerifying, setIsVerifying] = useState(false);
    const [error, setError] = useState(null);
    const inputsRef = useRef([]);

    useEffect(() => {
        if (isOpen && inputsRef.current[0]) {
            inputsRef.current[0].focus();
        }
    }, [isOpen]);

    const handleChange = (index, value) => {
        if (!/^[0-9]*$/.test(value)) return;

        const newCode = [...code];
        newCode[index] = value;
        setCode(newCode);

        if (value && index < 5) {
            inputsRef.current[index + 1]?.focus();
        }

        if (newCode.every(v => v !== '')) {
            submitVerification(newCode.join(''));
        }
    };

    const handleKeyDown = (index, e) => {
        if (e.key === 'Backspace' && !code[index] && index > 0) {
            inputsRef.current[index - 1]?.focus();
        }
    };

    const submitVerification = async (fullCode) => {
        setIsVerifying(true);
        setError(null);
        try {
            await onVerify(fullCode);
            setCode(['', '', '', '', '', '']);
        } catch (err) {
            setError(err.message || 'Invalid code. Please try again.');
            setCode(['', '', '', '', '', '']);
            inputsRef.current[0]?.focus();
        } finally {
            setIsVerifying(false);
        }
    };

    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#0F172A]/80 backdrop-blur-sm p-4">
            <div className="bg-white rounded-3xl shadow-2xl w-full max-w-md overflow-hidden relative">
                <button 
                    onClick={onClose} 
                    className="absolute right-6 top-6 text-slate-400 hover:text-slate-700 transition-colors focus:outline-none"
                >
                    <XCircle className="w-6 h-6" />
                </button>
                
                <div className="p-8 text-center">
                    <div className="w-16 h-16 rounded-full bg-[#1B4D3E]/10 text-[#1B4D3E] flex items-center justify-center mx-auto mb-4">
                        <ShieldAlert className="w-8 h-8" />
                    </div>
                    
                    <h3 className="text-2xl font-extrabold text-[#1B4D3E] tracking-tight">Two-Step Verification</h3>
                    <p className="text-sm text-slate-500 mt-2 mb-8 leading-relaxed">
                        Enter the 6-digit authentication code generated by your authenticator app to access the Admin Control Center.
                    </p>

                    {error && (
                        <div className="mb-6 p-3 rounded-xl bg-red-50 text-red-600 text-sm font-bold border border-red-100">
                            {error}
                        </div>
                    )}

                    <div className="flex justify-between max-w-xs mx-auto mb-8">
                        {code.map((digit, index) => (
                            <input
                                key={index}
                                ref={el => inputsRef.current[index] = el}
                                type="text"
                                maxLength={1}
                                value={digit}
                                onChange={(e) => handleChange(index, e.target.value)}
                                onKeyDown={(e) => handleKeyDown(index, e)}
                                disabled={isVerifying}
                                className="w-12 h-14 text-center text-xl font-bold rounded-xl border-slate-200 focus:border-[#D97706] focus:ring-[#D97706] bg-slate-50 disabled:opacity-50"
                            />
                        ))}
                    </div>

                    <button 
                        onClick={() => submitVerification(code.join(''))}
                        disabled={isVerifying || code.join('').length !== 6}
                        className="w-full py-4 rounded-xl bg-[#1B4D3E] hover:bg-[#13382d] text-white font-bold tracking-wide transition-all disabled:opacity-70 disabled:cursor-not-allowed shadow-md shadow-[#1B4D3E]/20 flex items-center justify-center gap-2"
                    >
                        {isVerifying ? (
                            <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                        ) : (
                            'Verify & Continue'
                        )}
                    </button>
                </div>
            </div>
        </div>
    );
}
